name: Build and test flake outputs
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        nix-command:
          - build .#manPages
          - build .#manualHtml
          - build .#optionsJson
          - flake check
          - fmt

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v19
        with:
          extra_nix_config: |
            keep-going = true
            show-trace = true

      - name: Run ${{ matrix.nix-command }}
        run: nix ${{ matrix.nix-command }}
