name: Build and test flake outputs
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        nix-command:
          - build .#manPages
          - build .#manualHtml
          - build .#optionsJson
          - flake check
          - fmt

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v18

      - name: Run ${{ matrix.nix-command }}
        run: |
          nix \
            --print-build-logs \
            --option keep-going true \
            --show-trace \
            ${{ matrix.nix-command }}
